dist: xenial
services:
- postgresql
addons:
<<<<<<< HEAD
  postgresql: '9.4' hey
=======
  postgresql: '9.4'
>>>>>>> c918d255c2b5d6ff3f94db9995a3602f7e239f9e
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd decide
- cp local_settings1.py local_settings.py
- python ./manage.py test --keepdb -v 2
notifications:
  email:
    recipients:
    - one@example.com
    - other@example.com
    on_success: never
    on_failure: never
